# Generated by Django 6.0.1 on 2026-09-29 21:08

import django.db.models.deletion
import furniture.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('id_number', models.CharField(blank=True, max_length=13, verbose_name='Cédula / RUC')),
                ('phone', models.CharField(max_length=20, verbose_name='Celular / WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cliente (Muebles)',
                'verbose_name_plural': 'Clientes (Muebles)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('kind', models.CharField(choices=[('RETAPIZADO', 'Retapizado'), ('FABRICACION', 'Fabricación')], max_length=15, verbose_name='Tipo de trabajo')),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('LISTO', 'Listo para entregar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='RECIBIDO', max_length=15, verbose_name='Estado')),
                ('observations', models.TextField(blank=True, verbose_name='Estado actual / Observaciones')),
                ('requirements', models.TextField(blank=True, verbose_name='Requerimientos del cliente')),
                ('deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Abono')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('owner_signature', models.ImageField(blank=True, null=True, upload_to='furniture/signatures/')),
                ('owner_signer_name', models.CharField(blank=True, max_length=120)),
                ('client_signature', models.ImageField(blank=True, null=True, upload_to='furniture/signatures/')),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('company_snapshot', models.JSONField(blank=True, default=dict)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='furniture.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hoja de entrada',
                'verbose_name_plural': 'Hojas de entrada',
                'ordering': ['-created_at'],
            },
            bases=(furniture.models.ItemsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Cantidad')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitario')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='furniture.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='furniture/orders/%Y/%m/')),
                ('stage', models.CharField(choices=[('ACTUAL', 'Estado actual'), ('REFERENCIA', 'Referencia / diseño'), ('AVANCE', 'Avance'), ('TERMINADO', 'Terminado')], default='ACTUAL', max_length=12)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='furniture.order')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('kind', models.CharField(choices=[('RETAPIZADO', 'Retapizado'), ('FABRICACION', 'Fabricación')], default='RETAPIZADO', max_length=15, verbose_name='Tipo de trabajo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=15)),
                ('notes', models.TextField(blank=True, verbose_name='Detalle / condiciones')),
                ('valid_days', models.PositiveIntegerField(default=15, verbose_name='Validez (días)')),
                ('company_snapshot', models.JSONField(blank=True, default=dict)),
                ('public_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='furniture.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-created_at'],
            },
            bases=(furniture.models.ItemsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='furniture.quote', verbose_name='Proforma de origen'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('description', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='furniture.quote')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuotePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='furniture/quotes/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='furniture.quote')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('LISTO', 'Listo para entregar'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], max_length=15)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='furniture.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['at'],
            },
        ),
    ]
