# Generated by Django 6.0.5 on 2026-05-22 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('opening_time', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Apertura')),
                ('closing_time', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Cierre')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Inicial')),
                ('system_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total en Sistema')),
                ('declared_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Declarado (Físico)')),
                ('discrepancy', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia (Sobrante/Faltante)')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10, verbose_name='Estado de Caja')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones de Cierre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cajero / Vendedor')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-opening_time'],
            },
        ),
    ]
