# Generated by Django 6.0.5 on 2026-05-23 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_register', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashsession',
            old_name='discrepancy',
            new_name='difference',
        ),
        migrations.RemoveField(
            model_name='cashsession',
            name='declared_balance',
        ),
        migrations.RemoveField(
            model_name='cashsession',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cashsession',
            name='system_balance',
        ),
        migrations.AddField(
            model_name='cashsession',
            name='actual_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Efectivo Físico Real'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='expected_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo Esperado'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='is_open',
            field=models.BooleanField(default=True, verbose_name='Estado de Caja'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='total_card',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Tarjeta'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='total_cash',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Efectivo Vendido'),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='total_transfer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Transferencias'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='closing_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cierre'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Fondo Inicial'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='opening_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Apertura'),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Cajero/Vendedor'),
        ),
    ]
