# Generated by Django 6.0.1 on 2026-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SELLER', 'Vendedor'), ('MUEBLES', 'Muebles M&L')], default='SELLER', max_length=10, verbose_name='Rol del Usuario'),
        ),
    ]
