# Generated by Django 6.0.5 on 2026-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('U', 'Unidades'), ('ML', 'Mililitros (Líquidos)')], default='U', max_length=2, verbose_name='Tipo de Unidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio de Compra'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_critico',
            field=models.DecimalField(decimal_places=2, default=2.0, max_digits=10, verbose_name='Stock Crítico'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.CharField(default='Unidad', max_length=50, verbose_name='Unidad de Medida / Presentación'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
    ]
