# Generated by Django 6.0.5 on 2026-05-27 17:24

import customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cedula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[customers.validators.validate_ecuadorian_cedula], verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
    ]
