# Generated by Django 6.0.1 on 2026-09-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('slug', models.SlugField(unique=True, verbose_name='Identificador interno')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre comercial')),
                ('legal_name', models.CharField(blank=True, max_length=160, verbose_name='Razón social / Propietario')),
                ('ruc', models.CharField(blank=True, max_length=13, verbose_name='RUC')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono / WhatsApp')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='Logo')),
                ('document_notes', models.TextField(blank=True, help_text='Ej: garantía, plazos de retiro, formas de pago.', verbose_name='Condiciones al pie de los documentos')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['name'],
            },
        ),
    ]
