# Generated by Django 6.0.5 on 2026-06-02 03:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_address_alter_customer_cedula_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('color', models.CharField(max_length=30, verbose_name='Color')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='Kilometraje')),
                ('left_helmet', models.BooleanField(default=False)),
                ('left_keys', models.BooleanField(default=True)),
                ('left_registration', models.BooleanField(default=False)),
                ('fuel_level', models.CharField(default='1/2', help_text='Ej: Reserva, 1/4, 1/2, Lleno', max_length=20)),
                ('issue_description', models.TextField(verbose_name='Falla reportada / Motivo de ingreso')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Abono Inicial ($)')),
                ('status', models.CharField(choices=[('pending', 'Pendiente / En Espera'), ('in_progress', 'En Reparación'), ('ready', 'Listo (Terminado)'), ('delivered', 'Entregado al Cliente')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_signature_base64', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='workshop/%Y/%m/')),
                ('is_video', models.BooleanField(default=False, help_text='Marca si es un video')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='workshop.serviceorder')),
            ],
        ),
    ]
