# Generated by Django 6.0.5 on 2026-06-02 03:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_alter_customer_cedula_and_more'),
        ('inventory', '0003_product_unit_type_alter_product_purchase_price_and_more'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicemedia',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripción opcional'),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='media_file',
            field=models.FileField(upload_to='workshop/%Y/%m/', verbose_name='Archivo Multimedia'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='client_signature_base64',
            field=models.TextField(blank=True, null=True, verbose_name='Firma Digital'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Finalización'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_orders', to='customers.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='fuel_level',
            field=models.CharField(default='1/2', help_text='Ej: Reserva, 1/4, 1/2, Lleno', max_length=20, verbose_name='Nivel de Combustible'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='left_helmet',
            field=models.BooleanField(default=False, verbose_name='Dejó Casco'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='left_keys',
            field=models.BooleanField(default=True, verbose_name='Dejó Llaves'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='left_registration',
            field=models.BooleanField(default=False, verbose_name='Dejó Matrícula'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente / En Espera'), ('in_progress', 'En Reparación'), ('ready', 'Listo (Terminado)'), ('delivered', 'Entregado al Cliente')], default='pending', max_length=20, verbose_name='Estado de la Orden'),
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción (Mano de obra o Repuesto)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario ($)')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Repuesto Físico')),
                ('service_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workshop.serviceorder')),
            ],
        ),
    ]
