# Generated by Django 6.0.5 on 2026-06-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_alter_servicemedia_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceorder',
            name='issue_description',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='left_helmet',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='left_keys',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='left_registration',
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='arrived_by_crane',
            field=models.BooleanField(default=False, verbose_name='Ingreso en Grúa'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='condition_checklist',
            field=models.JSONField(blank=True, default=dict, verbose_name='Estado de la Motocicleta (B/M)'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='customer_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observación y Peticiones del Cliente'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='damage_map_data',
            field=models.JSONField(blank=True, default=list, verbose_name='Puntos del Mapa de Daños'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='detailed_inventory',
            field=models.JSONField(blank=True, default=list, verbose_name='Inventario Detallado'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Técnicas Generales'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Serie / Chasis'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='work_to_do',
            field=models.TextField(blank=True, default='', verbose_name='Trabajo a Realizar'),
        ),
        migrations.AlterField(
            model_name='servicemedia',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Comentario / Detalle de la foto'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='fuel_level',
            field=models.CharField(default='1/2', max_length=20, verbose_name='Nivel de Combustible'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='mileage',
            field=models.PositiveIntegerField(default=0, verbose_name='Kilometraje Ingreso'),
        ),
    ]
