# Generated by Django 6.0.5 on 2026-06-03 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_remove_serviceorder_issue_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='left_helmet',
            field=models.BooleanField(default=False, verbose_name='Dejó Casco'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='left_keys',
            field=models.BooleanField(default=False, verbose_name='Dejó Llaves'),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='left_registration',
            field=models.BooleanField(default=False, verbose_name='Dejó Matrícula'),
        ),
    ]
