# Generated by Django 6.0.5 on 2026-06-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_serviceorder_left_helmet_serviceorder_left_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='intake_pdf',
            field=models.FileField(blank=True, null=True, upload_to='workshop/pdfs/intakes/', verbose_name='PDF de Ingreso'),
        ),
    ]
