# Generated by Django 6.0.5 on 2026-05-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_sale_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='historical_cost',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Costo Compra Histórico'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='historical_price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12, verbose_name='Precio Venta Histórico'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Precio Unitario Aplicado'),
        ),
    ]
