# Generated by Django 6.0.5 on 2026-05-28 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_unit_type_alter_product_purchase_price_and_more'),
        ('sales', '0004_saledetail_historical_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='Es Mano de Obra'),
        ),
        migrations.AddField(
            model_name='saledetail',
            name='service_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción del Servicio'),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto'),
        ),
    ]
