# Generated by Django 6.0.5 on 2026-05-29 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_saledetail_is_service_saledetail_service_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venta / Proforma', 'verbose_name_plural': 'Ventas y Proformas'},
        ),
        migrations.AddField(
            model_name='sale',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Saldo Pendiente'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PROFORMA', 'Proforma'), ('DRAFT', 'Borrador (Pre-Factura)'), ('INVOICED', 'Facturado'), ('VOIDED', 'Anulado')], default='PROFORMA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='sale',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válido hasta (Proforma)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Abonado')),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('CARD', 'Tarjeta'), ('MIXED', 'Mixto')], default='TRANSFER', max_length=20, verbose_name='Método de Pago')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Comprobante / Referencia')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Pago Verificado')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale', verbose_name='Factura Relacionada')),
            ],
            options={
                'verbose_name': 'Abono / Pago',
                'verbose_name_plural': 'Abonos y Pagos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
