# Generated by Django 6.0.5 on 2026-05-30 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_address_alter_customer_cedula_and_more'),
        ('sales', '0006_alter_sale_options_sale_balance_due_sale_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer', verbose_name='Cliente'),
        ),
    ]
